model:
  _target_: src.models.diffusion.ddpm
  params:
    beta_end: 0.05
    schedule: linear
    timestep: 200
    is_conditional: True
    criterion: utils.metrics.MetricName
    use_ema: True
    lr_warmup: 5000
    lr_scheduler_config:
      _target_: torch.optim.lr_scheduler.MultiStepLR
      params:
        milestones: [5, 10, 20]
        gamma: 0.1

    optimizer_config:
      target: torch.optim.Adam
      params:
        lr: 1e-4

    unet_config:
      target: models.networks.unet_lucas
      params:
        dim: 200
        init_dim: None
        dim_mult: [1, 2, 4]
        channels: 1
        resnet_block_groups: 8
        learned_sinusoidal_dim: 16
