defaults:
  - model: unet_conditional
  - dataset: sequence
  - logger: wandb
  - callbacks: default

ckpt: null # path to checkpoint
seed: 42
batch_size: 32
devices: gpu
benchmark: True
ckpt_dir: null
accelerator: gpu
strategy: ddp
min_epochs: 5
max_epochs: 100000
gradient_clip_val: 1.0
accumulate_grad_batches: 1
log_every_n_steps: 1
check_val_every_n_epoch: 1 #for debug purposes
save_last: True
precision: 32
